development:
  adapter: postgresql
  encoding: unicode
  database: railslink_development
  host: localhost
  pool: 5
  username: <%= ENV['PG_USER'] || 'railslink' %>
  password: <%= ENV['PG_PASSWORD'] || 'railspgpw' %>

test:
  adapter: postgresql
  encoding: unicode
  database: railslink_test
  host: localhost
  pool: 5
  username: <%= ENV['PG_USER'] || 'railslink' %>
  password: <%= ENV['PG_PASSWORD'] || 'railspgpw' %>
